; Generated by generate-idt, DO NOT EDIT

idt:
    dw isr_0, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_1, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_2, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_3, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_4, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_5, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_6, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_7, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_8, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_9, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_10, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_11, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_12, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_13, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_14, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_15, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_16, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_17, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_18, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_19, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_20, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_21, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_22, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_23, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_24, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_25, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_26, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_27, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_28, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_29, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_30, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_31, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_32, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_33, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_34, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_35, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_36, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_37, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_38, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_39, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_40, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_41, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_42, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_43, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_44, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_45, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_46, kernel_code_gdte - gdt, 0x8e00, 0x0000
    dw isr_47, kernel_code_gdte - gdt, 0x8e00, 0x0000

idtr:
    idt_size: dw idtr - idt
    idt_base: dd idt

master_pic_start: db 32
slave_pic_start: db 40

isr_0:
    cli
    push 0
    jmp isr

isr_1:
    cli
    push 1
    jmp isr

isr_2:
    cli
    push 2
    jmp isr

isr_3:
    cli
    push 3
    jmp isr

isr_4:
    cli
    push 4
    jmp isr

isr_5:
    cli
    push 5
    jmp isr

isr_6:
    cli
    push 6
    jmp isr

isr_7:
    cli
    push 7
    jmp isr

isr_8:
    cli
    push 8
    jmp isr

isr_9:
    cli
    push 9
    jmp isr

isr_10:
    cli
    push 10
    jmp isr

isr_11:
    cli
    push 11
    jmp isr

isr_12:
    cli
    push 12
    jmp isr

isr_13:
    cli
    push 13
    jmp isr

isr_14:
    cli
    push 14
    jmp isr

isr_15:
    cli
    push 15
    jmp isr

isr_16:
    cli
    push 16
    jmp isr

isr_17:
    cli
    push 17
    jmp isr

isr_18:
    cli
    push 18
    jmp isr

isr_19:
    cli
    push 19
    jmp isr

isr_20:
    cli
    push 20
    jmp isr

isr_21:
    cli
    push 21
    jmp isr

isr_22:
    cli
    push 22
    jmp isr

isr_23:
    cli
    push 23
    jmp isr

isr_24:
    cli
    push 24
    jmp isr

isr_25:
    cli
    push 25
    jmp isr

isr_26:
    cli
    push 26
    jmp isr

isr_27:
    cli
    push 27
    jmp isr

isr_28:
    cli
    push 28
    jmp isr

isr_29:
    cli
    push 29
    jmp isr

isr_30:
    cli
    push 30
    jmp isr

isr_31:
    cli
    push 31
    jmp isr

isr_32:
    cli
    push 32
    jmp isr

isr_33:
    cli
    push 33
    jmp isr

isr_34:
    cli
    push 34
    jmp isr

isr_35:
    cli
    push 35
    jmp isr

isr_36:
    cli
    push 36
    jmp isr

isr_37:
    cli
    push 37
    jmp isr

isr_38:
    cli
    push 38
    jmp isr

isr_39:
    cli
    push 39
    jmp isr

isr_40:
    cli
    push 40
    jmp isr

isr_41:
    cli
    push 41
    jmp isr

isr_42:
    cli
    push 42
    jmp isr

isr_43:
    cli
    push 43
    jmp isr

isr_44:
    cli
    push 44
    jmp isr

isr_45:
    cli
    push 45
    jmp isr

isr_46:
    cli
    push 46
    jmp isr

isr_47:
    cli
    push 47
    jmp isr
